name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'council-website/**'

jobs:
  deploy:
    name: Deploy Council website

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs mkdocs-material

      - name: Generate and deploy
        working-directory: ./council-website
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          mkdocs gh-deploy --force --no-history
